FROM arm32v7/alpine:latest AS production
ENV PROJECT_PATH=/chirpstack-gateway-bridge
ENV PATH=$PATH:$PROJECT_PATH
RUN mkdir -p $PROJECT_PATH
WORKDIR $PROJECT_PATH
RUN wget https://artifacts.chirpstack.io/downloads/chirpstack-gateway-bridge/chirpstack-gateway-bridge_3.5.0_linux_armv7.tar.gz
RUN tar xvzf chirpstack-gateway-bridge_3.5.0_linux_armv7.tar.gz
ENTRYPOINT ["chirpstack-gateway-bridge"]
