FROM arm32v7/alpine:latest AS production
ENV PROJECT_PATH=/chirpstack-application-server
ENV PATH=$PATH:$PROJECT_PATH
RUN mkdir -p $PROJECT_PATH
WORKDIR $PROJECT_PATH
RUN wget https://artifacts.chirpstack.io/downloads/chirpstack-application-server/chirpstack-application-server_3.6.0_linux_armv7.tar.gz
RUN tar xvzf chirpstack-application-server_3.6.0_linux_armv7.tar.gz
ENTRYPOINT ["chirpstack-application-server"]
